title = "Han"
theme = "flat"
themesDir = "themes"
enableRobotsTXT = true
hasCJKLanguage = true
paginate = 4
baseURL = "https://zzuhann-blog.github.io/"
post = "/:slug/"

# these values are hugo built in markup config
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = false
noClasses = false
noHl = false
style = 'monokailight'
tabWidth = 4

[params]
description = "Example site for hugo-theme-flat"
mainSections = ['posts']

## uncomment belows and set proper values to enable remark42
# [params.remark42]
# host=''
# site_id=''
# max_shown_comments=100
# theme='light'
# locale='en'
# show_email_subscription=false
# simple_view=true


[[menus.main]]
name = "Posts"
url = "/posts/"
weight = 30

[[menus.main]]
pageref = "about"
name = "About"
weight = 80

[taxonomies]
  tag = "tags"
  series = "series"
  category = "categories"